language: node_js
node_js: lts/*
git:
  depth: 1
install: yarn
cache: yarn
script: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $_TOKEN
  keep_history: true
  committer_from_gh: true
  target_branch: master
  on:
    branch: master